import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/app/components/sidebar";
import Topbar from "@/app/components/topbar";
import Player from "@/app/components/player";
import { DataProvider } from "@/app/contexts/data-context";
import { PlaybackProvider } from "@/app/contexts/playback-context";
import AudioElement from "@/app/components/audio-element";

const acidGrotesk = localFont({
  src: [
    { path: "./fonts/FFF-AcidGrotesk-Normal-TRIAL.otf", weight: "400" },
    { path: "./fonts/FFF-AcidGrotesk-Bold-TRIAL.otf", weight: "700" },
  ],
  variable: "--font-acid-grotesk",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={acidGrotesk.className}>
      <body
        className={`${acidGrotesk.variable} ${geistMono.variable} antialiased bg-dark text-light grid grid-cols-[96px_1fr] grid-rows-[72px_auto] p-4 gap-4`}
      >
        <DataProvider>
          <PlaybackProvider>
            <Sidebar className="col-start-1 row-start-1" />
            <Topbar className="col-start-2 col-span-1 row-start-1 sticky top-4" />
            <div className="col-start-2 row-start-2 mb-48">{children}</div>
            <Player className="fixed bottom-0 left-0" />
            <AudioElement />
          </PlaybackProvider>
        </DataProvider>
      </body>
    </html>
  );
}
