import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const acidGrotesk = localFont({
  src: [
    { path: "./fonts/FFF-AcidGrotesk-Normal-TRIAL.otf", weight: "400" },
    { path: "./fonts/FFF-AcidGrotesk-Bold-TRIAL.otf", weight: "700" },
  ],
  variable: "--font-acid-grotesk",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={acidGrotesk.className}>
      <body
        className={`${acidGrotesk.variable} ${geistMono.variable} antialiased bg-dark text-light`}
      >
        {children}
      </body>
    </html>
  );
}
